### ISSUE TITLE
Python 3 error

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#19]
On my system:

```
$ python3 ~/dev/nlp-tools/DepEdit/depedit/depedit.py -c fixhash.depedit.ini "reviews/*.conllu"
Traceback (most recent call last):
  File "/Users/nathan/dev/nlp-tools/DepEdit/depedit/depedit.py", line 862, in <module>
    main(parser.parse_args())
  File "/Users/nathan/dev/nlp-tools/DepEdit/depedit/depedit.py", line 838, in main
    f.write(output_trees.encode("utf-8"))
TypeError: write() argument must be str, not bytes
```

**Comment by amir-zeldes** [comment]
Thanks for reporting, should be fixed now (and deployed to PyPI)

**Comment by nschneid** [comment]
Confirmed fixed
